### PR TITLE
Add JEKYLL_ENV=production to Gulp's build task

### PR DESCRIPTION
**Pull request by eksperimental**
Fixes https://github.com/core77/jekyll-foundation/pull/40#issuecomment-264845968

### CODE REVIEW

**Comment by core77** [comment]
I'm wondering in the jekyll config you check if the environment is 'development' (to ignore the compress.html layout).

In the jekyll gulp task you set 'production'. 

Where ist the 'development' environment beeing set?

**Comment by eksperimental** [comment]
according to Jekyll documentation, 'development' is the default environment

**Comment by eksperimental** [comment]
another way of doing this is to define the ENV in `package.json`
```
  "scripts": {
    "start": "gulp",
    "build": "JEKYLL_ENV=production gulp build --production",
    "test": "JEKYLL_ENV=production gulp build --production"
  },
```

but doing it inside gulp allows us to call `gulp` directly

**Comment by core77** [comment]
👍

**Pull request merged**
